languageCode: "en-us"
defaultContentLanguage: "en"
enableRobotsTXT: true
enableEmoji: true

theme: "almeida-cv"
disableKinds: 
  - "page"
  - "section"
  - "taxonomy"
  - "term"
  - "RSS"
  - "sitemap"

baseURL: "https://cv.bennysbytes.dev/"
title: "Ben Vilnis - CV"

params:
  enableMetaTags: true
  colorLight: "#fff"
  colorDark: "#666"
  colorPageBackground: "#ddd"
  colorPrimary: "#86a0c2"
  colorSecondary: "#aaa"
  colorIconPrimary: "#fff"
  colorIconBackground: "#86a0c2"
  colorRightColumnBackground: "#f5f5f5"
  colorRightColumnHeadingText: "#666"
  colorRightColumnBodyText: "#666"
  colorRightColumnIconPrimary: "#fff"
  colorRightColumnIconBackground: "#86a0c2"
  pages: 1
  # Set this param to 'true' to swap the bar positions
  swapColumns: false
